name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to master if your default branch is master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-python: '3.8'

      - name: Install Zola
        run: |
          sudo wget -q -O /usr/bin/zola https://github.com
          sudo chmod +x /usr/bin/zola

      - name: Run Netlify Build Command
        env:
          LANDING_BUTTON: "Browse notes!"
          LANDING_DESCRIPTION: ""
          LANDING_PAGE: "./readme"
          LANDING_TITLE: "Joe's Notes"
          REPO_URL: "https://github.com/joeGermany/JoeNotes"
          SITE_TITLE: "Joe Germany"
          SITE_TITLE_TAB: ""
          SITE_URL: "https://github.io" # Replace with your actual GitHub Pages URL
          TIMEZONE: "Asia/Hong_Kong"
          ZOLA_VERSION: "0.15.2"
          SORT_BY: "title"
          SLUGIFY: "y"
          HOME_GRAPH: "y"
          PAGE_GRAPH: ""
          SIDEBAR_COLLAPSED: "y"
          GRAPH_OPTIONS: |
            {
              nodes: {
                shape: "dot",
                color: isDark() ? "#8c8e91" : "#dee2e6",
                font: {
                  face: "Inter",
                  color: isDark() ? "#c9cdd1" : "#616469",
                  strokeColor: isDark() ? "#c9cdd1" : "#616469",
                },
                scaling: {
                  label: {
                    enabled: true,
                  },
                },
              },
              edges: {
                color: { inherit: "both" },
                width: 0.8,
                smooth: {
                  type: "continuous",
                },
                hoverWidth: 4,
              },
              interaction: {
                hover: true,
              },
              height: "100%",
              width: "100%",
              physics: {
                solver: "repulsion",
              },
            }
        run: |
          rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true 
          git clone https://github.com/joeGermany/obsidian-zola-plus.git __site 
          __site/run.sh

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
